### ISSUE TITLE
Unable to access Google Cloud Storage bucket

### ISSUE THREAD

**Issue by sbhambr1** [abdulhaim/LMRL-Gym#1]
Hi, I am unable to run the first command to train the BC model using: 
`python llm_rl_scripts/maze/bc/fully_observed_bc.py HF gpt2 gcs://rl-llm-bench-dataset-internal/maze/fully_observed_maze_data.jsonl --outputs-path bc_checkpoint_path`

I am receiving the following error:

> OSError: Forbidden: b/rl-llm-bench-dataset-internal/o
> <username@email.com> does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
> 

Any help is appreciated!

**Comment by sbhambr1** [comment]
As a followup on the details of the issue, I also checked https://rail.eecs.berkeley.edu/datasets/rl-llm-bench-dataset/ which also does not provide access to download the datasets.

**Comment by DT6A** [comment]
Having the same issue. Any updates on that?

**Comment by icwhite** [comment]
Hi! Thank you for bringing this to our attention. The `python llm_rl_scripts/maze/bc/fully_observed_bc.py HF gpt2 gcs://rl-llm-bench-dataset-internal/maze/fully_observed_maze_data.jsonl --outputs-path bc_checkpoint_path` command should work now that we have properly configured permissions. 

We are still working on making the https://rail.eecs.berkeley.edu/datasets/rl-llm-bench-dataset/ bucket accessible to outside users. This will be resolved within the week.

Thank you for your patience!

**Comment by icwhite** [comment]
We have made the bucket private again. Please download the datasets from this link:   https://rail.eecs.berkeley.edu/datasets/rl-llm-bench-dataset/
