### ISSUE TITLE
jax_models problems

### ISSUE THREAD

**Issue by DT6A** [abdulhaim/LMRL-Gym#2]
Hello! I'm trying to run the `llm_rl_scripts/car_dealer/bc/train_bc.py` but it fails with the following error:

```
Traceback (most recent call last):
  File "/home/user/LMRL-Gym/llm_rl_scripts/car_dealer/bc/train_bc.py", line 6, in <module>
    from jax_models.gpt2 import load_gpt2_model
ModuleNotFoundError: No module named 'jax_models'
```

I followed all of the installation instructions. Any suggestions what could go wrong?

**Comment by icwhite** [comment]
Hi DT6A, thank you for letting us know about the issue! Could you let us know what hardware you are running on? We will try to reproduce the issue. 

My guess is that the wrong version of a package is installed. The installation instructions are different depending on whether you are running on CPU, GPU or TPU.

**Comment by DT6A** [comment]
Hi, I was trying CPU installation

**Comment by DT6A** [comment]
@icwhite hi! Any updates on that?

**Comment by icwhite** [comment]
Hi! This is an issue with an older version of the package. We will fix this problem soon. Thank you for your patience.

**Comment by DT6A** [comment]
@icwhite, OK, thanks for your response!

**Comment by icwhite** [comment]
Hi @DT6A!  Apologies for the delay but the bc script for Car Dealer is now functional!

**Comment by DT6A** [comment]
Thank you!
